spring.application.name=Spring-Security-jdbc-2
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8098
spring.datasource.username=root
spring.datasource.password=12345
spring.datasource.url=jdbc:mysql://localhost:3306/zepto
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true